### ISSUE TITLE
Create a configuration where Rivet can fall back to RivetSimulator

### ISSUE THREAD

**Issue by msgilligan** [rivetz/RivetzJ#26]
Create a library method that can dynamically determine if the Rivet TA is supported and, if so, load the `Rivet` implementation of the Rivet API. Otherwise fall back to the `RivetSimulator` implementation.

@greglaun : Any comments?

**Comment by greglaun** [comment]
This exists in Rivetz Core and Rivetz FTS. We can think about the best way to make it reusable across Android projects.
