### ISSUE TITLE
Rename this repository

### ISSUE THREAD

**Issue by msgilligan** [rivetz/RivetzJ#3]
@mespr should it be *RivetzJ* or *RivetJ*?

**Comment by msgilligan** [comment]
I vote for *RivetzJ*. Consistent branding, better SEO, etc. (though one fewer character is also appealing)

**Comment by mespr** [comment]
I agree. Rivet is the instance name, and the verb.

**Comment by msgilligan** [comment]
I assigned this to you, @mespr since you have administration rights to this repository.

**Comment by msgilligan** [comment]
@mespr I see you've renamed it. You should also change the repo title from
> Helper class for interfacing with Rivetz

to something else.

**Comment by msgilligan** [comment]
@mespr There is also a URL you can set that goes right next to the repository title. I recommend setting it to [https://rivetz.com/docs/](https://rivetz.com/docs/).

**Comment by msgilligan** [comment]
Closing.
